name:                lab2
version:             0.1.0.0
github:              "ProgMiner/lab2"
author:              "Eridan Domoratskiy"
maintainer:          "eridan200@mail.ru"
copyright:           "Copyright (c) Eridan Domoratskiy"
# license:             MIT

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
# description:         Please see the README on GitHub at <https://github.com/ProgMiner/lab2#readme>

dependencies:
- base >= 4.7 && < 5
- mmap
- wx

library:
  source-dirs: src
  extra-lib-dirs:
  - ./btrfs/
  extra-libraries:
  - btrfs

executables:
  lab2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab2

tests:
  lab2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lab2
